# Generated by Django 6.0.2 on 2026-03-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_branch_service_remove_member_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='postcode',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
    ]
